# FROM node:20-alpine
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY . .
# RUN npm run build
# EXPOSE 3000
# CMD ["npm", "start"]

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install   # <--- Change this line
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]